name: ultimate_chat


services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./search_service/searxng:/etc/searxng:rw  # Updated volume path
    ports:
      - "8080:8080"
    networks:
      - app-network



  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    

  search-service:
    build:
      context: ./search_service
    container_name: search-service
    ports:
      - "3001:3001"
    depends_on:
      - searxng
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    networks:
      - app-network

  main-backend-service:
    build:
      context: ./main_backend_service
    container_name: main-backend-service
    depends_on:
      - search-service
      - redis
    ports:
      - "5001:5001"
    environment: # enable while need auto reload after code changes
      # - FLASK_ENV=development
      # - FLASK_APP=app.py 
      - NODE_BACKEND_URL=http://search-service:3001 # never give space befor and after equal(=) sign
      - REDIS_HOST=redis
    # volumes:   # enable while need auto reload after code changes
    #   - ./main_backend_service:/app
    #   - /app/venv  
    networks:
      - app-network

  main-frontend-service:
    build:
      context: ./main_frontend_service
    container_name: main-frontend-service
    depends_on:
      - main-backend-service
      - redis
    ports:
      - "3000:3000"
    # volumes: # enable while need auto reload after code changes
    #   - ./main_frontend_service:/app
    
    environment:
      - NEXT_PUBLIC_MAIN_BACKEND_SERVICE_URL=http://localhost:5001
      - MAIN_BACKEND_SERVICE_URL=http://main-backend-service:5001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
