name: Continuous Integration  # Name of the workflow

on:
  # push:
  #   branches:
  #     - main  # Runs CI when pushing to the "main" branch
  pull_request:
    branches:
      - main  # Runs CI when opening a pull request

jobs:

  landing-service-ci:
    name: Landing Service CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: landing_service
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
      - run: npm run build




  Main-Service-ci:
    name: Main Service CI
    runs-on: ubuntu-latest  # The OS where the workflow runs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches your repo code

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Enables advanced Docker builds

      - name: Build Docker Images
        run: |
          docker compose build  

      
